// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsXJcEzQp8OtfGxIcP_9CW7gwmIzXnTUQ',
    appId: '1:94893429682:web:274a6aab9c73343f1ccaab',
    messagingSenderId: '94893429682',
    projectId: 'polynomial-11334',
    authDomain: 'polynomial-11334.firebaseapp.com',
    storageBucket: 'polynomial-11334.appspot.com',
    measurementId: 'G-ERR0PLSRTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq3dUxb0iehyLFlbivWLiRzc0x1NWussM',
    appId: '1:94893429682:android:c21142c1c8ace1601ccaab',
    messagingSenderId: '94893429682',
    projectId: 'polynomial-11334',
    storageBucket: 'polynomial-11334.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf7bybubgXRYuvaLA6uVY6XAB1yeNIn6A',
    appId: '1:94893429682:ios:1e38f6ba5b1817521ccaab',
    messagingSenderId: '94893429682',
    projectId: 'polynomial-11334',
    storageBucket: 'polynomial-11334.appspot.com',
    iosClientId: '94893429682-cprq0rgre994g0b5de5ntemrqk0mfgkp.apps.googleusercontent.com',
    iosBundleId: 'polynomial',
  );
}
